routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) {
        return redirect('feed');
    } else {
        return view('welcome');
    }
});

Route::get('/auth/google', [AuthController::class, 'googleRedirect']);
Route::get('/auth/google/callback', [AuthController::class, 'handleGoogleLogin']);
Route::get('/auth/facebook', [AuthController::class, 'facebookRedirect']);
Route::get('/auth/facebook/callback', [AuthController::class, 'handleFacebookLogin']);
Route::get('/auth/twitter', [AuthController::class, 'twitterRedirect']);
Route::get('/auth/twitter/callback', [AuthController::class, 'handleTwitterLogin']);

Route::get('/feed', [PostController::class, 'feedView'])->name('feed')->middleware('auth');

Route::get('/discover', function () {
    return view('discover');
})->name('discover')->middleware('auth');

Route::get('/publish', [PostController::class, 'publishView'])->name('publish')->middleware('auth');

Route::post('/publish', [PostController::class, 'store'])->middleware('auth');

Route::get('/discover', [PostController::class, 'discoverView'])->name('discover')->middleware('auth');

Route::get('/user/{user}', [UserController::class, 'userView'])->name('user')->middleware('auth');

Route::get('/post/{post}', [PostController::class, 'postView'])->name('post')->middleware('auth');

Route::post('/post/{post}/comment', [CommentController::class, 'store'])->name('comment')->middleware('auth');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePostRequest;
use App\Models\Content;
use App\Models\Post;
use App\Models\Tag;
use Carbon\Carbon;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostRequest $request)
    {
        $premium = $request->input('premium');
        $validated = $request->validated();
        $post = new Post();
        $post->title = $validated['title'];
        $post->description = $validated['description'];
        $post->premium = (bool)$premium;
        $tags = json_decode($validated['tags']);
        DB::transaction(function () use ($request, $tags, $post) {
            $request->user()->posts()->save($post);
            foreach ($tags as $tag) {
                $tagInstance = Tag::firstOrCreate(['name' => Str::lower($tag->value)]);
                $post->tags()->save($tagInstance);
            }
        });
        DB::transaction(function () use ($post, $request) {
            $i = 0;
            foreach ($request->file('file') as $file) {
                $url = Storage::put('public/contents', $file, 'public');
                $content = new Content();
                $content->position = $i;
                $content->url = $url;
                $mimeType = $file->getMimeType();
                switch ($mimeType) {
                    case Str::startsWith($mimeType, 'image'):
                        $contentType = 'photo';
                        break;
                    case Str::startsWith($mimeType, 'video'):
                        $contentType = 'video';
                        break;
                    default:
                        DB::rollBack();
                        throw new Exception('Invalid file type supplied');
                }
                $content->type = $contentType;
                $post->contents()->save($content);
                $i++;
            }
        });
        // Force refresh the user in the search index (mostly to fix invisible users that were not indexed)
        $request->user()->save();
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
    }

    public function feedView(Request $request)
    {
        $subscriptions = $request->user()->subscriptions()->withCount(['posts', 'subscribers'])->get();
        $posts = Post::whereIn('user_id', $subscriptions->pluck('id'))->with(['user', 'contents', 'tags'])->with(['likes' => function ($query) use ($request) {
            return $query->where('user_id', $request->user()->id);
        }])->withCount(['likes', 'comments'])->orderBy('created_at', 'desc')->get();
        return view('feed', ['posts' => $posts, 'subscriptions' => $subscriptions]);
    }

    public function publishView(Request $request)
    {
        $posts = $request->user()->posts()->orderBy('created_at', 'desc')->with(['contents'])->get();
        return view('publish', ['posts' => $posts]);
    }

    public function discoverView(Request $request)
    {
        $tagsId = DB::table('post_tag')->select('tag_id')->join('posts', 'posts.id', '=', 'post_tag.post_id')->where('posts.premium', false)->groupBy('tag_id')->orderByDesc(DB::raw('count(tag_id)'))->limit(5)->get()->pluck('tag_id');
        $tags = Tag::whereIn('id', $tagsId)->with(['tenPosts' => function ($query) use ($request) {
            return $query->where('premium', false)->with(['likes' => function ($query) use ($request) {
                return $query->where('user_id', $request->user()->id);
            }])->withCount(['likes', 'comments']);
        }, 'tenPosts.contents', 'tenPosts.user' => function ($query) use ($request) {
            return $query->withCount(['posts', 'subscribers'])->with(['subscribers' => function ($query) use ($request) {
                return $query->where('users.id', $request->user()->id);
            }]);
        }])->get();
        $likes = DB::table('likes')->select('likeable_id', 'id')->join('likeables', 'likes.id', '=', 'likeables.like_id')->where('user_id', $request->user()->id)->get();
        $recommendedTagsIds = DB::table('tags')->select('id')->join('post_tag', 'tags.id', '=', 'post_tag.tag_id')->whereIn('post_tag.post_id', $likes->pluck('likeable_id'))->limit(5)->get()->pluck('id');
        $recommendedPosts = Post::whereHas('tags', function ($query) use ($recommendedTagsIds) {
            return $query->whereIn('id', $recommendedTagsIds);
        })->whereDoesntHave('likes', function ($query) use ($likes) {
            return $query->whereIn('id', $likes->pluck('id'));
        })->where('premium', false)->with(['likes' => function ($query) use ($request) {
            return $query->where('user_id', $request->user()->id);
        }, 'tags', 'contents', 'user' => function ($query) use ($request) {
            return $query->withCount(['posts', 'subscribers'])->with(['subscribers' => function ($query) use ($request) {
                return $query->where('users.id', $request->user()->id);
            }]);
        }])->withCount(['likes', 'comments'])->limit(10)->inRandomOrder()->get();
        return view('discover', ['tags' => $tags, 'recommendedPosts' => $recommendedPosts]);
    }

    public function postView(Post $post, Request $request)
    {
        $post->load(['contents', 'user' => function ($query) use ($request) {
            return $query->withCount(['posts', 'subscribers'])->with(['subscribers' => function ($query) use ($request) {
                return $query->where('user_id', $request->user()->id);
            }]);
        }, 'likes' => function ($query) use ($request) {
            return $query->where('user_id', $request->user()->id);
        }, 'tags', 'comments' => function ($query) use ($request) {
            return $query->with(['likes' => function ($query) use ($request) {
                $query->where('user_id', $request->user()->id);
            }, 'user' => function ($query) use ($request) {
                return $query->withCount(['posts', 'subscribers'])->with(['subscribers' => function ($query) use ($request) {
                    $query->where('user_id', $request->user()->id);
                }]);
            }])->orderByDesc('created_at')->withCount(['likes']);
        }])->loadCount(['likes', 'comments']);
        $hasValidSubscription = ($post->user->subscribers->count() > 0 && Carbon::now() < $post->user->subscribers->first()->pivot->expires_at);
        return view('post', ['post' => $post, 'hasValidSubscription' => $hasValidSubscription]);
    }

    public function deletePost(Request $request, Post $post)
    {
        DB::transaction(function () use ($post) {
            $post->comments()->delete();
            $post->tags()->detach();
            $post->contents()->delete();
            $post->delete();
        });
        $request->user()->save();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function userView(User $user, Request $request)
    {
        $user->load(['posts' => function ($query) {
            return $query->latest()->limit(10)->withCount(['comments', 'likes']);
        }, 'posts.contents', 'subscribers' => function($query) use ($request) {
            return $query->where('user_id', $request->user()->id);
        }, 'posts.likes' => function ($query) use ($request) {
            return $query->where('user_id', $request->user()->id);
        }, 'posts.tags'])->loadCount(['subscribers', 'posts']);
        $hasValidSubscription = ($user->subscribers->count() > 0 && Carbon::now() < $user->subscribers->first()->pivot->expires_at);
        return view('user', ['user' => $user, 'hasValidSubscription' => $hasValidSubscription]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('onlyfrogz.dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/discover.blade.php
@extends('layouts.onlyfrogz')
@section('title',__('onlyfrogz.discover'))
@section('content')
    <header>
        <h1 class="onlyfrogzPageTitle">{{__('onlyfrogz.discover')}}</h1>
    </header>
    <section class="onlyfrogzPopularTags">
        @foreach($tags as $tag)
            <span class="onlyfrogzTag" style="background-color: {{$tag->color}}">{{$tag->name}}
            </span>
            <div class="onlyfrogzPostsPerTag">
                @foreach($tag->tenPosts as $post)
                    <div class="onlyfrogzPostPerTag">
                        <div class="swiper-container">
                            <div class="swiper-wrapper">
                                @foreach($post->contents as $content)
                                    <div class="swiper-slide">
                                        @switch($content->type)
                                            @case("video")
                                            <video src="{{$content->url}}" controls>
                                                @break
                                                @case("photo")
                                                <img src="{{$content->url}}">
                                            @break
                                        @endswitch
                                    </div>
                                @endforeach
                            </div>
                            <div class="swiper-pagination"></div>
                            <div class="swiper-button-prev"></div>
                            <div class="swiper-button-next"></div>
                        </div>
                        <div class="onlyfrogzPostDiscover">
                            <div class="onlyfrogzCircleAvatar onlyfrogzCircleAvatarDiscover">
                                <a href="{{route('user',$post->user)}}">
                                    <img src="{{$post->user->profile_photo_url}}"
                                         alt="{{__('onlyfrogz.altprofilepicture',['name' => $post->user->name])}}">
                                </a>
                                <div class="onlyfrogzUserInfoPanel onlyfrogzUserInfoPanelDiscover">
                                    <div>
                                        <h3>{{$post->user->name}}</h3>
                                        <span><b>{{$post->user->subscribers_count}} </b>{{trans_choice('onlyfrogz.subscribers',$post->user->subscribers_count)}}</span>
                                        <span><b>{{$post->user->posts_count}} </b>{{trans_choice('onlyfrogz.posts', $post->user->posts_count)}}</span>
                                        @if($post->user->subscribers->count() > 0)
                                            <button data-content-creator-id="{{$post->user->id}}"
                                                    class="onlyfrogzUnsubscribe">{{__('onlyfrogz.unsubscribe')}}</button>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <a href="{{route('post',$post)}}">
                                <h2 class="onlyfrogzPostTitleDiscover">{{$post->title}}</h2>
                            </a>
                            <div class="onlyfrogzSocial">
                                <button data-post-id="{{$post->id}}" class="onlyfrogzLikePost">{{$post->likes_count}} <i
                                        class="{{$post->likes->count() > 0 ? "fas" : "far"}} fa-heart"></i></button>
                                <span>{{$post->comments_count}} <i class="far fa-comments"></i></span>
                                <button data-post-id="{{$post->id}}" class="onlyfrogzShare"><i
                                        class="fas fa-share-alt"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                    </a>
                @endforeach
            </div>
        @endforeach
    </section>
    <h1 class="onlyfrogzPageTitle">{{__('onlyfrogz.recommended')}}</h1>
    <div class="onlyfrogzAllPostsFeed">
        @foreach($recommendedPosts as $post)
            <article class="onlyfrogzPostContainer">
                <div class="onlyfrogzAvatarAndSocialContainer">
                    <div class="onlyfrogzCircleAvatar">
                        <a href="{{route('user',$post->user)}}">
                            <img src="{{$post->user->profile_photo_url}}"
                                 alt="{{__('onlyfrogz.altprofilepicture',['name' => $post->user->name])}}">
                        </a>
                        <div class="onlyfrogzUserInfoPanel">
                            <div>
                                <h3>{{$post->user->name}}</h3>
                                <span><b>{{$post->user->subscribers_count}} </b>{{trans_choice('onlyfrogz.subscribers',$post->user->subscribers_count)}}</span>
                                <span><b>{{$post->user->posts_count}} </b>{{trans_choice('onlyfrogz.posts', $post->user->posts_count)}}</span>
                                @if($post->user->subscribers->count() > 0)
                                    <button data-content-creator-id="{{$post->user->id}}"
                                            class="onlyfrogzUnsubscribe">{{__('onlyfrogz.unsubscribe')}}</button>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="onlyfrogzSocial">
                        <button data-post-id="{{$post->id}}" class="onlyfrogzLikePost">{{$post->likes_count}} <i
                                class="{{$post->likes->count() > 0 ? "fas" : "far"}} fa-heart"></i></button>
                        <span>{{$post->comments_count}} <i class="far fa-comments"></i></span>
                        <button data-post-id="{{$post->id}}" class="onlyfrogzShare"><i class="fas fa-share-alt"></i>
                        </button>
                    </div>
                </div>
                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        @foreach($post->contents as $content)
                            <div class="swiper-slide">
                                @switch($content->type)
                                    @case("video")
                                    <video src="{{$content->url}}" controls>
                                        @break
                                        @case("photo")
                                        <img src="{{$content->url}}">
                                    @break
                                @endswitch
                            </div>
                        @endforeach
                    </div>
                    <div class="swiper-pagination"></div>
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>
                </div>
                <a href="{{route('post',$post)}}">
                    <div class="onlyfrogzPostTextContainer">
                        <p class="onlyfrogzPostDescription">{{Str::limit($post->description,200)}}</p>
                        <div>
                            <div class="onlyfrogzTags">
                                @foreach($post->tags as $tag)
                                    <span style="background-color: {{$tag->color}}">{{$tag->name}}</span>
                                @endforeach
                            </div>
                            <h2 class="onlyfrogzPostTitle">{{$post->title}}
                                @if($post->premium)
                                    <i class="fas fa-star"></i>
                                @endif
                            </h2>
                        </div>
                    </div>
                </a>
            </article>
        @endforeach
    </div>
@endsection

resources/views/feed.blade.php
@extends('layouts.onlyfrogz')
@section('title',__('onlyfrogz.feed'))
@section('content')
    <header>
        <h1 class="onlyfrogzPageTitle">{{__('onlyfrogz.feed')}}</h1>
    </header>
    @if($posts->count() == 0)
        <h2 class="onlyfrogzEmptyFeed">{{__('onlyfrogz.emptyfeedfirstpart')}}<a
                href="{{route('discover')}}">{{__('onlyfrogz.emptyfeedlink')}}</a><span>{{__('onlyfrogz.emptyfeedlastpart')}}</span>
        </h2>
    @endif
    <div class="onlyfrogzAllPostsFeed">
        @foreach($posts as $post)
            <article class="onlyfrogzPostContainer">
                <?php
                $author = $subscriptions->find($post->user);
                $hasAccess = !($post->premium && $author->pivot->expires_at < \Carbon\Carbon::now());
                ?>
                <div class="onlyfrogzAvatarAndSocialContainer">
                    <div class="onlyfrogzCircleAvatar">
                        <a href="{{route('user',$author)}}">
                            <img src="{{$author->profile_photo_url}}"
                                 alt="{{__('onlyfrogz.altprofilepicture',['name' => $post->user->name])}}">
                        </a>
                        <div class="onlyfrogzUserInfoPanel">
                            <div>
                                <h3>{{$author->name}}</h3>
                                <span><b>{{$author->subscribers_count}} </b>{{trans_choice('onlyfrogz.subscribers',$author->subscribers_count)}}</span>
                                <span><b>{{$author->posts_count}} </b>{{trans_choice('onlyfrogz.posts', $author->posts_count)}}</span>
                                @if($post->user->subscribers->count() > 0)
                                    <button data-content-creator-id="{{$post->user->id}}"
                                            class="onlyfrogzUnsubscribe">{{__('onlyfrogz.unsubscribe')}}</button>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="onlyfrogzSocial">
                        @if($hasAccess)
                            <button data-post-id="{{$post->id}}" class="onlyfrogzLike onlyfrogzLikePost">{{$post->likes_count}} <i
                                    class="{{$post->likes->count() > 0 ? "fas" : "far"}} fa-heart"></i></button>
                            <span>{{$post->comments_count}} <i class="far fa-comments"></i></span>
                            <button data-post-id="{{$post->id}}" class="onlyfrogzShare"><i
                                    class="fas fa-share-alt"></i>
                            </button>
                        @endif
                    </div>
                </div>
                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        @foreach($post->contents as $content)
                            <div class="swiper-slide">
                                @switch($content->type)
                                    @case("video")
                                    <video src="{{$content->url}}"
                                           style="filter:{{ !$hasAccess ? 'blur(10px) saturate(0.3)': 'none'}};"
                                           {{!$hasAccess && "muted"}} controls>
                                        @break
                                        @case("photo")
                                        <img src="{{$content->url}}" alt=""
                                             style="filter:{{ !$hasAccess ? 'blur(10px) saturate(0.3)': 'none'}};">
                                    @break
                                @endswitch
                            </div>
                        @endforeach
                    </div>
                    <div class="swiper-pagination"></div>
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>
                </div>
                <a href="{{route('post',$post)}}">
                    <div class="onlyfrogzPostTextContainer">
                        @if($hasAccess)
                            <p class="onlyfrogzPostDescription">{{Str::limit($post->description,200)}}</p>
                        @else
                            <p class="onlyfrogzPostPremiumDescription">{{__('onlyfrogz.premium', ['name' => $post->user->name])}}</p>
                        @endif
                        <div>
                            <div class="onlyfrogzTags">
                                @foreach($post->tags as $tag)
                                    <span style="background-color: {{$tag->color}}">{{$tag->name}}</span>
                                @endforeach
                            </div>
                            <h2 class="onlyfrogzPostTitle">{{$post->title}}
                                @if($post->premium)
                                    <i class="fas fa-star"></i>
                                @endif
                            </h2>
                        </div>
                    </div>
                </a>
            </article>
        @endforeach
    </div>
@endsection

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/publish.blade.php
@extends('layouts.onlyfrogz')
@section('title',__('onlyfrogz.publish'))
@section('content')
    <header>
        <h1 class="onlyfrogzPageTitle">{{__('onlyfrogz.publish')}}</h1>
    </header>
    <form enctype="multipart/form-data" method="POST" action="/publish" class="onlyfrogzUploadContainer">
        @csrf
        <div class="onlyfrogzUploadLeftPanel">
            <input required type="file" name="file[]" class="onlyfrogzFileUploader">
            <div class="onlyfrogzUploadButtons">
                <input type="submit" class="onlyfrogzConfirmUpload" value="{{__('onlyfrogz.confirm')}}">
                <button type="reset" class="onlyfrogzCancelUpload">{{__('onlyfrogz.cancel')}}</button>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
        </div>
        <div class="onlyfrogzUploadRightPanel">
            <textarea required class="onlyfrogzUploadPostDescription" maxlength="500" name="description"
                      rows="6" cols="50" placeholder="{{__('onlyfrogz.inputpostdescription')}}"></textarea>
            <input placeholder="{{__('onlyfrogz.inputposttag')}}" name="tags"
                   class="onlyfrogzUploadTags">
            <input required type="text" class="onlyfrogzUploadPostTitle" maxlength="60" name="title"
                   placeholder="{{__('onlyfrogz.inputposttitle')}}">
            <input name="premium" class="onlyfrogzUploadCheckbox" type="checkbox"><i
                title="{{__('onlyfrogz.startooltip')}}"
                class="onlyfrogzUploadPremium far fa-2x fa-star"></i>
        </div>
    </form>
    <h1 class="onlyfrogzPageTitle">{{__('onlyfrogz.lastposts')}}</h1>
    @if($posts->count() == 0)
        <h2 class="onlyfrogzEmptyFeed onlyfrogzEmptyLastPosts">{{__('onlyfrogz.emptylastposts')}}</h2>
    @endif
    <div class="onlyfrogzPersonnalPostContainer">
        @foreach($posts as $post)
            <article class="onlyfrogzPostPublish">
                <a href="{{route('post',$post)}}">
                    <h3 class="onlyfrogzPostTitlePublish">{{$post->title}}</h3>
                    <div class="swiper-container onlyfrogzPostSlidePublish">
                        <div class="swiper-wrapper">
                            @foreach($post->contents as $content)
                                <div class="swiper-slide">
                                    @switch($content->type)
                                        @case("video")
                                        <video src="{{$content->url}}" muted controls>
                                            @break
                                            @case("photo")
                                            <img src="{{$content->url}}" alt="">
                                            @break
                                            @endswitch
                                            <img src="{{$content->url}}" alt="">
                                </div>
                            @endforeach
                        </div>
                        <div class="swiper-pagination"></div>
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-button-next"></div>
                    </div>
                    <button data-post-id="{{$post->id}}"
                            class="onlyfrogzCancelUpload onlyfrogzDeletePostButton">{{__('onlyfrogz.deletepost')}} <i
                            class="far fa-trash-alt"></i>
                    </button>
                </a>
            </article>
        @endforeach
    </div>
@endsection

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>